CREATE TABLE `perfumes` (
	`id` text PRIMARY KEY NOT NULL,
	`catalog_id` text,
	`name` text NOT NULL,
	`brand` text NOT NULL,
	`line` text,
	`concentration` text NOT NULL,
	`year` integer,
	`gender` text NOT NULL,
	`family` text,
	`bottle_size_ml` integer,
	`fill_level` real DEFAULT 100 NOT NULL,
	`batch_code` text,
	`purchased_at` integer,
	`purchase_price` real,
	`purchase_currency` text,
	`purchase_location` text,
	`is_gift` integer DEFAULT false NOT NULL,
	`rating` real,
	`is_favorite` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'owned' NOT NULL,
	`notes` text,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`deleted_at` integer
);
